# Generated by Django 2.1.4 on 2019-01-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='subscriber',
            fields=[
                ('email', models.CharField(max_length=150)),
                ('subscriber_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
