# Generated by Django 2.1.4 on 2019-03-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='propety',
            name='lister',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
