# Generated by Django 2.1.4 on 2019-03-15 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0002_propety_lister'),
    ]

    operations = [
        migrations.AddField(
            model_name='propety',
            name='status',
            field=models.CharField(blank=True, choices=[('C', 'Complete'), ('P', 'Pending')], max_length=10),
        ),
    ]
