# Generated by Django 2.1.4 on 2019-02-07 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_agent'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='property',
            new_name='propety',
        ),
    ]
