# Generated by Django 2.1.4 on 2019-03-15 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0003_propety_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booked_viewings',
            name='client',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booked_viewings',
            name='time',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
