# Generated by Django 2.1.4 on 2019-02-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0004_auto_20190207_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_on_property',
            name='property_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
