# Generated by Django 2.1.4 on 2019-02-12 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0007_auto_20190211_1001'),
    ]

    operations = [
        migrations.DeleteModel(
            name='agent',
        ),
    ]
