# Generated by Django 2.1.4 on 2019-02-12 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MySite', '0009_agent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agent',
            old_name='user_id',
            new_name='user',
        ),
    ]
